### ISSUE TITLE
创建用户报错

### ISSUE THREAD

**Issue by gaoyuke** [enilu/material-admin#5]
首先把系统自带的部门删除，然后自己添加几个部门，再创建几个角色，再去创建用户时，user_add.html的第十三行@for(dict in constant.getDicts('性别')){报错。并且，当修改过部门名称后，角色所属部门名称未更新。

**Comment by enilu** [comment]
检查下字典表t_sys_dict数据是否初始化成功,如果没有，查看import.sql，将字典表数据手动插入

**Comment by gaoyuke** [comment]
字典表初始化成功了

**Comment by enilu** [comment]
贴具体错误信息
